# Generated by Django 3.0 on 2021-11-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='watch_seller',
            new_name='seller',
        ),
    ]
